name: Integration
on: 
  pull_request:
    branches:
      - main
jobs:
  Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Pull compose.yaml from another repository
        run: |
          git clone https://github.com/mskz-ptplus-jp/docker-php83.git
          cp docker-php83/compose.yaml .
          cp -r docker-php83/docker ./docker
      - name: Setup
        run: |
          npm install
          npx playwright install
          docker compose up -d
      - name: Install Composer dependencies
        run: |
          CONTAINER_ID=$(docker ps --filter "name=app" -q)
          docker exec -w /var/www/html $CONTAINER_ID composer install
      - name: Run Static Test
        run: npm run test:static
      - name: Run Unit Test
        run: npm run test:unit
      - name: Run E2E Test
        run: npm run test:e2e
